'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    ar: {
        // Sidebar & Navigation
        nav_home: 'الرئيسية',
        nav_scan: 'محطة المسح',
        nav_customers: 'العملاء',
        nav_cards: 'البطاقات',
        nav_discounts: 'الخصومات',
        nav_campaigns: 'إدارة الباقات',
        nav_transactions: 'سجل العمليات',
        nav_management: 'سجلات النظام',
        nav_terminals: 'مراقب الأجهزة',
        nav_logs: 'سجلات التدقيق',
        nav_settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        welcome: 'مرحباً',
        topup_btn: 'شحن رصيد / باقة',
        no_packages_title: 'لا توجد باقات',
        no_packages_desc: 'يرجى إنشاء باقات جديدة في مدير الباقات',
        days_label: 'يوم',
        discount: 'خصم',

        // Generic Actions
        add: 'إضافة',
        edit: 'تعديل',
        delete: 'حذف',
        save: 'حفظ',
        cancel: 'إلغاء',
        search: 'بحث...',
        loading: 'جاري التحميل...',
        no_data: 'لا توجد بيانات',
        actions: 'الإجراءات',
        status: 'الحالة',
        is_active: 'نشط',
        all_branches: 'كل الفروع',
        confirm: 'تأكيد',
        close: 'إغلاق',

        // Scan Page
        waiting_card: 'في انتظار البطاقة',
        scan_desc: 'ضع البطاقة على القارئ للبدء',
        processing: 'جاري المعالجة...',
        customer_not_found: 'العميل غير موجود',
        card_not_linked: 'البطاقة غير متصلة',
        total_savings: 'إجمالي التوفير',
        bill_amount: 'قيمة الفاتورة',
        pay_with_wallet: 'دفع من المحفظة',
        pay_cash: 'دفع نقدي',
        insufficient_balance: 'الرصيد غير كافٍ',
        active_packages: 'الباقات المتاحة',
        no_active_packages: 'لا توجد باقات جاهزة للاستخدام',
        credit_unit: 'باقة',
        customer_wallet: 'رصيد المحفظة',
        recharge_btn: 'شحن رصيد / شراء باقة',
        manual_topup: 'شحن رصيد نقدي',
        manual_topup_desc: 'إضافة رصيد مالي لمحفظة العميل',
        recharge_confirm_btn: 'إتمام الشحن',
        error_invalid_amount: 'يرجى إدخال مبلغ صحيح',
        scanning_effect: 'جاري المسح الضوئي...',
        saving_value: 'لقد وفرت {value} حتى الآن!',
        active_status: 'نشط',
        admin_controls: 'أدوات الإدارة',
        connection_error: 'خطأ في الاتصال',
        reset_confirm_title: 'تأكيد التصفير',
        build_status: 'حالة النظام',
        version_label: 'الإصدار',

        // Admin Tools
        admin_reset_balance: 'تصفير الرصيد',
        admin_clear_packages: 'تفريغ الباقات',
        confirm_reset_balance: 'هل أنت متأكد من تصفير الرصيد النقدي نهائياً؟',
        confirm_clear_packages: 'هل أنت متأكد من حذف كافة الباقات من البطاقة؟',
        reset_success: 'تم تنفيذ العملية بنجاح',
        reset_failed: 'فشلت العملية',
        network_error: 'خطأ في الاتصال',

        // Wallet
        topup_select_package: 'اختر الباقة المناسبة',
        empty_wallet: 'المحفظة فارغة',
        valid_until: 'صالح حتى',
        use_now: 'استخدم الآن',
        selected: 'تم الاختيار',
        confirm_use_btn: 'تأكيد الاستخدام',
        cancel_btn: 'إلغاء',
        coupon_used: 'تم استخدام الباقة بنجاح!',
        coupon_use_failed: 'فشل في استخدام الباقة',
        no_expiry: 'بدون تاريخ انتهاء',
        purchase_confirm: 'هل أنت متأكد من شراء {name} مقابل {price}؟',
        package_details: 'تفاصيل الباقة',
        price: 'السعر',
        usage_limit: 'عدد الوحدات',
        per_unit: 'لكل باقة',
        have_balance_msg: 'لديك رصيد متاح في المحفظة، يمكنك استخدامه لشراء باقات وعروض.',
        empty_wallet_desc: 'المحفظة فارغة تماماً، قم بشحن الرصيد للبدء في استخدام الخدمات.',

        // Settings Page
        settings_title: 'إعدادات النظام',
        settings_desc: 'تخصيص وإدارة تجربة النظام الخاصة بك',
        save_changes: 'حفظ التغييرات',
        tab_general: 'عام',
        tab_finance: 'المالية',
        tab_appearance: 'المظهر',
        tab_system: 'النظام',
        tab_developer: 'أدوات المطور',
        store_name: 'اسم المتجر',
        toast_duration: 'مدة التنبيهات (ms)',
        currency_symbol: 'رمز العملة',
        accent_color: 'اللون الأساسي',
        system_sounds: 'أصوات النظام',
        maintenance_mode: 'وضع الصيانة',
        maintenance_desc: 'إيقاف دخول غير الموظفين للنظام مؤقتاً',
        emergency_admin_restore: 'استعادة مدير النظام',
        emergency_admin_desc: 'إعادة إنشاء حساب المسؤول الافتراضي (admin/admin)',
        developer_notice: 'هذه الأدوات مخصصة للاستخدام التقني فقط. التلاعب بها قد يؤدي لتعطيل النظام.',
        upload_logo: 'رفع شعار',
        uploading: 'جاري الرفع...',
        logo_guide: 'دليل الشعار',
        logo_rec_square: 'يفضل استخدام شعار مربع أو دائري لتناسق القوائم.',
        logo_rec_wide: 'يفضل شفافية الخلفية (PNG).',
        logo_max_size: 'الحد الأقصى الموصى به: 2MB',
        system_info: 'حالة النظام',
        db_connection: 'اتصال البيانات',
        api_status: 'حالة الملقم',
        version: 'الإصدار',
        restart_system: 'إعادة تشغيل النظام',
        clear_cache: 'تفريغ الذاكرة المؤقتة',
        status_healthy: 'مستقر',
        status_active: 'نشط',
        on: 'مفعل',
        off: 'معطل',
        loading_settings: 'جاري تحميل الإعدادات...',
        save_success: 'تم حفظ التغييرات بنجاح',
        restore_success: 'تم استعادة المسؤول بنجاح',

        // Customers Page
        register_customer: 'تسجيل عميل جديد',
        show_deleted: 'الأرشيف',
        hide_deleted: 'الرجوع للقائمة',
        recycle_bin: 'سلة المحذوفات',
        customer_name: 'اسم العميل',
        card_uid: 'رقم البطاقة (UID)',
        customer_phone: 'رقم الهاتف',
        customer_email: 'البريد الإلكتروني',
        new_member_badge: 'عضوية جديدة',
        autofilled_msg: 'تم الملء تلقائياً من المسح',
        card_status_current: 'المتصل حالياً',
        card_status_available: 'متاح للاتصال',
        restore: 'استعادة',
        confirm_permanent_delete: 'هل أنت متأكد من حذف العميل نهائياً من قاعدة البيانات؟ لا يمكن التراجع عن هذا الإجراء.',
        promotion_badge: 'منطق العروض',

        // Campaigns Page
        campaigns_title: 'مدير الباقات',
        campaigns_desc: 'إنشاء وإدارة العروض الترويجية وباقات المشتريات',
        recycle_desc: 'الحملات التي تم حذفها مؤخراً',
        recycle_btn: 'العناصر المحذوفة',
        back_to_active: 'العودة للقائمة النشطة',
        new_campaign: 'إنشاء باقة جديدة',
        edit_campaign: 'تعديل الباقة',
        campaign_name: 'اسم الباقة / العرض',
        campaign_name_placeholder: 'مثال: باقة البريميوم، خصم الشتاء',
        campaign_description: 'وصف الباقة (اختياري)',
        campaign_description_placeholder: 'أضف تفاصيل إضافية عن الباقة...',
        validity_days: 'صلاحية الكوبونات (يوم)',
        reward_config: 'إعدادات الجائزة',
        reward_type: 'نوع الخصم',
        reward_percent: 'نسبة مئوية (%)',
        reward_fixed: 'مبلغ ثابت',
        reward_value: 'قيمة الخصم',
        launch_campaign: 'إطلاق الباقة',
        campaign_created_success: 'تم إنشاء الباقة بنجاح',
        type_auto_spend: 'تلقائي (حسب الإنفاق)',
        type_bundle: 'باقة مشتروات',
        type_manual: 'يدوي (إضافة مباشرة)',
        no_desc: 'لا يوجد وصف متاح لهذا العرض',
        trigger_rule_label: 'قاعدة التفعيل',
        rule_spend_above: 'عند إنفاق أكثر من',
        rule_collect_stamps: 'تجميع {count} طوابع / زيارات',
        rule_manual_only: 'يتم إضافته يدوياً للعملاء',
        reward_label: 'الجائزة المستحقة',
        off_label: 'خصم / باقة',
        delete_permanent: 'حذف نهائي',

        // Transactions & Logs
        status_success: 'مكتملة',
        status_failed: 'فاشلة',
        export_success: 'تم تصدير البيانات بنجاح',
        export: 'تصدير CSV',
        amount: 'المبلغ',
        date: 'التاريخ',
        customer_points: 'عدد الباقات',

        // Cards Page
        link_card: 'توصيل بطاقة جديدة',
        expires_at: 'تاريخ الانتهاء',
        connected: 'متصل',
        disconnected: 'غير متصل',
        card_registry_badge: 'سجل البطاقات',
        default_expiry_msg: 'الافتراضي: 3 أشهر من الآن',

        // Audit Logs
        audit_error_load: 'فشل تحميل سجلات التدقيق',
        audit_clear_success: 'تم مسح السجلات بنجاح',
        audit_clear_error: 'فشل في مسح السجلات',
        audit_all: 'الكل',
        audit_auth: 'الأمان',
        audit_customers: 'العملاء',
        audit_cards: 'البطاقات',
        audit_campaigns: 'الحملات',
        audit_track_desc: 'مراقبة كافة التغييرات والعمليات الحساسة في النظام',
        audit_timestamp: 'الوقت',
        audit_admin: 'المسؤول',
        audit_action: 'العملية',
        audit_entity: 'الهدف',
        audit_details: 'التفاصيل',
        audit_no_logs: 'لا توجد سجلات مطابقة للبحث',
        audit_clear_confirm: 'تأكيد مسح السجلات',
        audit_clear_desc: 'سيتم مسح كافة سجلات التدقيق نهائياً. يرجى إدخال كلمة المرور للتأكيد.',
        action_create: 'إضافة',
        action_update: 'تعديل',
        action_delete: 'حذف',
        action_restore: 'استعادة',
        action_login: 'دخول',
        system: 'نظام آلي',

        // Management & Enterprise
        enterprise_management: 'إدارة المؤسسة',
        enterprise_desc: 'إدارة الفروع، الأجهزة، والمستخدمين من مكان واحد',
        tabs_branches: 'الفروع',
        tabs_terminals: 'الأجهزة',
        tabs_users: 'المستخدمين',
        add_branch: 'إضافة فرع',
        add_terminal: 'إضافة جهاز',
        add_user: 'إضافة مستخدم',
        branch_name: 'اسم الفرع',
        branch_location: 'الموقع',
        terminal_name: 'اسم الجهاز',
        terminal_branch: 'الفرع',
        terminal_secret: 'مفتاح الربط',
        username: 'اسم المستخدم',
        password: 'كلمة المرور',
        role: 'الصلاحية',
        admin: 'مدير',
        staff: 'موظف',
        superadmin: 'مدير نظام',
        password_hint: 'اتركه فارغاً للحفاظ على كلمة المرور الحالية',
        online: 'متصل',
        offline: 'غير متصل',
        deactivated: 'معطل',
        deleted: 'محذوف',
        active: 'نشط',
        total_terminals: 'إجمالي الأجهزة',
        currently_online: 'متصل حالياً',
        hardware_alerts: 'تنبيهات الهاردوير',
        terminal_script_status: 'حالة السكريبت',
        terminal_nfc_reader: 'قارئ NFC',
        terminal_last_seen: 'آخر تواجد',
        disconnected_status: 'غير متصل',

        // Audit & Scan
        audit_clear: 'مسح السجلات',
        topup_modal_title: 'متجر الباقات',
        enterprise: 'المؤسسة',
        password: 'كلمة المرور',
        error_load: 'فشل تحميل البيانات',
        error_general: 'حدث خطأ ما',
        delete_success: 'تم الحذف بنجاح',
        delete_error: 'فشل الحذف',
        restore_error: 'فشل الاستعادة',
        confirm_delete: 'هل أنت متأكد من الحذف؟',
        topup_success: 'تمت عملية الشحن بنجاح',
    },
    en: {
        // Sidebar & Navigation
        nav_home: 'Home',
        nav_scan: 'Scan Terminal',
        nav_customers: 'Customers',
        nav_cards: 'Cards',
        nav_discounts: 'Discounts',
        nav_campaigns: 'Package Manager',
        nav_transactions: 'Transactions',
        nav_management: 'Management',
        nav_terminals: 'Terminal Monitor',
        nav_logs: 'Audit Logs',
        nav_settings: 'Settings',
        logout: 'Logout',
        welcome: 'Welcome',
        topup_btn: 'Top-up / Package',
        no_packages_title: 'No Packages',
        no_packages_desc: 'Please create new packages in Package Manager',
        days_label: 'Days',
        discount: 'Discount',

        // Generic Actions
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        search: 'Search...',
        loading: 'Loading...',
        no_data: 'No data available',
        actions: 'Actions',
        status: 'Status',
        is_active: 'Active',
        all_branches: 'All Branches',
        confirm: 'Confirm',
        close: 'Close',

        // Scan Page
        waiting_card: 'Waiting for Card',
        scan_desc: 'Place NFC card on reader to start',
        processing: 'Processing...',
        customer_not_found: 'Customer not found',
        card_not_linked: 'Card not linked',
        total_savings: 'Total Savings',
        bill_amount: 'Bill Amount',
        pay_with_wallet: 'Pay from Wallet',
        pay_cash: 'Cash Payment',
        insufficient_balance: 'Insufficient Balance',
        active_packages: 'Purchased Packages',
        no_active_packages: 'No active packages ready',
        credit_unit: 'Coupon',
        customer_wallet: 'Wallet Balance',
        recharge_btn: 'Top-up / Buy Package',
        manual_topup: 'Cash Top-up',
        manual_topup_desc: 'Add cash balance to customer wallet',
        recharge_confirm_btn: 'Complete Recharge',
        error_invalid_amount: 'Please enter a valid amount',
        scanning_effect: 'Scanning...',
        saving_value: 'You saved {value} so far!',
        active_status: 'Active',
        admin_controls: 'Administrative Controls',
        connection_error: 'Connection Error',
        reset_confirm_title: 'Confirm Reset',
        build_status: 'Build Status',
        version_label: 'VERSION',

        // Admin Tools
        admin_reset_balance: 'Reset Balance',
        admin_clear_packages: 'Clear Packages',
        confirm_reset_balance: 'Are you sure you want to permanently reset the cash balance?',
        confirm_clear_packages: 'Are you sure you want to remove all packages from the card?',
        reset_success: 'Operation completed successfully',
        reset_failed: 'Operation failed',
        network_error: 'Network Error',

        // Wallet
        topup_select_package: 'Select a Package',
        empty_wallet: 'Empty Wallet',
        valid_until: 'Valid until',
        use_now: 'Use Now',
        selected: 'Selected',
        confirm_use_btn: 'Confirm Use',
        cancel_btn: 'Cancel',
        coupon_used: 'Coupon used successfully!',
        coupon_use_failed: 'Failed to use coupon',
        no_expiry: 'No expiry date',
        purchase_confirm: 'Are you sure you want to buy {name} for {price}?',
        package_details: 'Package Details',
        price: 'Price',
        usage_limit: 'Units count',
        per_unit: 'Per Coupon',
        have_balance_msg: 'You have available balance in your wallet.',
        empty_wallet_desc: 'Wallet is completely empty. Recharge to start.',

        // Settings Page
        settings_title: 'System Settings',
        settings_desc: 'Customize and manage your system experience',
        save_changes: 'Save Changes',
        tab_general: 'General',
        tab_finance: 'Finance',
        tab_appearance: 'Appearance',
        tab_system: 'System',
        tab_developer: 'Developer Tools',
        store_name: 'Store Name',
        toast_duration: 'Toast Duration (ms)',
        currency_symbol: 'Currency Symbol',
        accent_color: 'Accent Color',
        system_sounds: 'System Sounds',
        maintenance_mode: 'Maintenance Mode',
        maintenance_desc: 'Temporarily disable non-staff access',
        emergency_admin_restore: 'Emergency Admin Restore',
        emergency_admin_desc: 'Restore default admin account (admin/admin)',
        developer_notice: 'These tools are for technical use only. Misuse may damage system integrity.',
        upload_logo: 'Upload Logo',
        uploading: 'Uploading...',
        logo_guide: 'Logo Guide',
        logo_rec_square: 'Square or round logos work best for icons.',
        logo_rec_wide: 'Transparent background (PNG) is recommended.',
        logo_max_size: 'Maximum recommended size: 2MB',
        system_info: 'System Information',
        db_connection: 'DB Connection',
        api_status: 'API Status',
        version: 'Version',
        restart_system: 'Restart Instance',
        clear_cache: 'Clear System Cache',
        status_healthy: 'Healthy',
        status_active: 'Active',
        on: 'ON',
        off: 'OFF',
        loading_settings: 'Loading Settings...',
        save_success: 'Settings saved successfully',
        restore_success: 'Admin restored successfully',

        // Customers Page
        register_customer: 'Register Customer',
        show_deleted: 'Show Deleted',
        hide_deleted: 'Hide Deleted',
        recycle_bin: 'Recycle Bin',
        customer_name: 'Customer Name',
        card_uid: 'Card UID',
        customer_phone: 'Phone Number',
        customer_email: 'Email Address',
        new_member_badge: 'New Member',
        autofilled_msg: 'Auto-filled from scan',
        card_status_current: 'Current',
        card_status_available: 'Available',
        restore: 'Restore',
        confirm_permanent_delete: 'Are you sure you want to delete this customer permanently? This action cannot be undone.',
        promotion_badge: 'Promotion Logic',

        // Campaigns Page
        campaigns_title: 'Package Manager',
        campaigns_desc: 'Create and manage promotions and purchase bundles',
        recycle_desc: 'Recently deleted campaigns and packages',
        recycle_btn: 'Recycle Bin',
        back_to_active: 'Back to Active',
        new_campaign: 'New Package',
        edit_campaign: 'Edit Package',
        campaign_name: 'Package/Campaign Name',
        campaign_name_placeholder: 'e.g., Premium Bundle, Winter Discount',
        campaign_description: 'Package Description (Optional)',
        campaign_description_placeholder: 'Add extra details about the package...',
        validity_days: 'Coupon Validity (Days)',
        reward_config: 'Reward Configuration',
        reward_type: 'Discount Type',
        reward_percent: 'Percentage (%)',
        reward_fixed: 'Fixed Amount',
        reward_value: 'Discount Value',
        launch_campaign: 'Launch Package',
        campaign_created_success: 'Package created successfully',
        type_auto_spend: 'Auto (Spend Base)',
        type_bundle: 'Bundle Package',
        type_manual: 'Manual Addition',
        no_desc: 'No description available for this offer',
        trigger_rule_label: 'Trigger Rule',
        rule_spend_above: 'Spend above',
        rule_collect_stamps: 'Collect {count} stamps/visits',
        rule_manual_only: 'Manually assigned to customers',
        reward_label: 'Earned Reward',
        off_label: 'OFF',
        delete_permanent: 'Delete Permanently',

        // Transactions & Logs
        status_success: 'SUCCESS',
        status_failed: 'FAILED',
        export_success: 'Data exported successfully',
        export: 'Export CSV',
        amount: 'Amount',
        date: 'Date',
        customer_points: 'Package Count',

        // Cards Page
        link_card: 'Link New Card',
        expires_at: 'Expires At',
        connected: 'Connected',
        disconnected: 'Disconnected',
        card_registry_badge: 'NFC Registry',
        default_expiry_msg: 'Default: 3 months from now',

        // Audit Logs
        audit_error_load: 'Failed to load audit logs',
        audit_clear_success: 'Logs cleared successfully',
        audit_clear_error: 'Failed to clear logs',
        audit_all: 'All',
        audit_auth: 'Security',
        audit_customers: 'Customers',
        audit_cards: 'Cards',
        audit_campaigns: 'Campaigns',
        audit_track_desc: 'Monitor all changes and sensitive operations in the system',
        audit_timestamp: 'Timestamp',
        audit_admin: 'Admin',
        audit_action: 'Action',
        audit_entity: 'Entity',
        audit_details: 'Details',
        audit_no_logs: 'No audit logs found',
        audit_clear_confirm: 'Confirm Clear Logs',
        audit_clear_desc: 'All audit logs will be permanently deleted. Enter password to confirm.',
        action_create: 'CREATE',
        action_update: 'UPDATE',
        action_delete: 'DELETE',
        action_restore: 'RESTORE',
        action_login: 'LOGIN',
        system: 'System Auto',

        // Management & Enterprise
        enterprise_management: 'Enterprise Management',
        enterprise_desc: 'Manage branches, terminals, and users from one place',
        tabs_branches: 'Branches',
        tabs_terminals: 'Terminals',
        tabs_users: 'Users',
        add_branch: 'Add Branch',
        add_terminal: 'Add Terminal',
        add_user: 'Add User',
        branch_name: 'Branch Name',
        branch_location: 'Location',
        terminal_name: 'Terminal Name',
        terminal_branch: 'Branch',
        terminal_secret: 'Terminal Secret',
        username: 'Username',
        password: 'Password',
        role: 'Role',
        admin: 'Admin',
        staff: 'Staff',
        superadmin: 'Super Admin',
        password_hint: 'Leave empty to keep current password',
        online: 'Online',
        offline: 'Offline',
        deactivated: 'Deactivated',
        deleted: 'Deleted',
        active: 'Active',
        total_terminals: 'Total Terminals',
        currently_online: 'Currently Online',
        hardware_alerts: 'Hardware Alerts',
        terminal_script_status: 'Script Status',
        terminal_nfc_reader: 'NFC Reader',
        terminal_last_seen: 'Last Seen',
        disconnected_status: 'Disconnected',

        // Audit & Scan
        audit_clear: 'Clear Logs',
        topup_modal_title: 'Package Store',
        enterprise: 'Enterprise',
        password: 'Password',
        error_load: 'Failed to load data',
        error_general: 'Something went wrong',
        delete_success: 'Deleted successfully',
        delete_error: 'Delete failed',
        restore_error: 'Restore failed',
        confirm_delete: 'Are you sure you want to delete?',
        topup_success: 'Top-up successful',
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('ar');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        const savedLang = localStorage.getItem('app_lang') || 'ar';
        setLanguage(savedLang);
        setMounted(true);
    }, []);

    useEffect(() => {
        if (mounted) {
            localStorage.setItem('app_lang', language);
            document.dir = language === 'ar' ? 'rtl' : 'ltr';
            document.lang = language;
        }
    }, [language, mounted]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
    };

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
