'use client';
import { useState, useEffect } from 'react';
import { useLanguage } from '@/lib/LanguageContext';
import { format } from 'date-fns';
import { Loader2, Database, Download, Clock, HardDrive } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase'; // Client side for download URL if needed

export default function BackupsPage() {
    const { language } = useLanguage();
    const [backups, setBackups] = useState([]);
    const [loading, setLoading] = useState(true);
    const [creating, setCreating] = useState(false);

    // Schedule State (Mock persistence)
    const [schedule, setSchedule] = useState('DAILY'); // OFF, DAILY, WEEKLY

    useEffect(() => {
        fetchBackups();
    }, []);

    const fetchBackups = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/backups');
            const data = await res.json();
            if (Array.isArray(data)) {
                setBackups(data);
            }
        } catch (error) {
            toast.error('Failed to load backups');
        } finally {
            setLoading(false);
        }
    };

    const handleCreateBackup = async () => {
        setCreating(true);
        try {
            const res = await fetch('/api/backups', { method: 'POST' });
            const data = await res.json();
            if (res.ok) {
                toast.success(language === 'ar' ? 'تم إنشاء النسخة الاحتياطية' : 'Backup created successfully');
                fetchBackups();
            } else {
                throw new Error(data.error);
            }
        } catch (error) {
            toast.error(error.message || 'Backup failed');
        } finally {
            setCreating(false);
        }
    };

    const handleDownload = async (fileName) => {
        try {
            // Request Signed URL from API (Securely generated by Admin)
            const res = await fetch(`/api/backups?action=download&file=${fileName}`);
            const data = await res.json();

            if (!res.ok) throw new Error(data.error);

            // Trigger download
            window.open(data.signedUrl, '_blank');
        } catch (error) {
            toast.error('Failed to generate download link');
        }
    };

    return (
        <div className="p-6 max-w-7xl mx-auto space-y-8" dir={language === 'ar' ? 'rtl' : 'ltr'}>

            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-gray-800 p-8 rounded-[2.5rem] shadow-sm border border-gray-100 dark:border-gray-700">
                <div>
                    <h1 className="text-3xl font-black text-gray-900 dark:text-white flex items-center gap-3">
                        <Database className="text-purple-600" size={32} />
                        {language === 'ar' ? 'النسخ الاحتياطي' : 'System Backups'}
                    </h1>
                    <p className="text-gray-500 mt-2 font-medium">
                        {language === 'ar' ? 'إدارة النسخ الاحتياطية لقاعدة البيانات والملفات' : 'Manage database and file backups'}
                    </p>
                </div>

                <button
                    onClick={handleCreateBackup}
                    disabled={creating}
                    className="flex items-center gap-2 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-xl shadow-purple-200 dark:shadow-none hover:scale-105 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {creating ? <Loader2 className="animate-spin" /> : <HardDrive size={20} />}
                    {language === 'ar' ? (creating ? 'جاري النسخ...' : 'نسخة يدوية الآن') : (creating ? 'Backing up...' : 'Manual Backup')}
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

                {/* Schedule Config */}
                <div className="lg:col-span-1 bg-white dark:bg-gray-800 p-6 rounded-[2rem] shadow-xl border border-gray-100 dark:border-gray-700 h-fit">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
                        <Clock className="text-orange-500" />
                        {language === 'ar' ? 'النسخ المجدول' : 'Scheduled Backup'}
                    </h3>

                    <div className="space-y-4">
                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all border-blue-500 bg-blue-50 dark:bg-blue-900/20">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'DAILY'}
                                    onChange={() => setSchedule('DAILY')}
                                    className="w-5 h-5 text-blue-600"
                                />
                                <span className="font-bold text-blue-900 dark:text-blue-100">
                                    {language === 'ar' ? 'يومياً (منتصف الليل)' : 'Daily (Midnight)'}
                                </span>
                            </label>
                        </div>

                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-gray-700 border-gray-200 dark:border-gray-600">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'WEEKLY'}
                                    onChange={() => setSchedule('WEEKLY')}
                                    className="w-5 h-5 text-gray-600"
                                />
                                <span className="font-bold text-gray-700 dark:text-gray-300">
                                    {language === 'ar' ? 'أسبوعياً' : 'Weekly'}
                                </span>
                            </label>
                        </div>

                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-gray-700 border-gray-200 dark:border-gray-600">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'OFF'}
                                    onChange={() => setSchedule('OFF')}
                                    className="w-5 h-5 text-gray-600"
                                />
                                <span className="font-bold text-gray-700 dark:text-gray-300">
                                    {language === 'ar' ? 'إيقاف' : 'Disabled'}
                                </span>
                            </label>
                        </div>
                    </div>

                    <button className="w-full mt-6 bg-gray-900 dark:bg-gray-700 text-white py-3 rounded-xl font-bold hover:bg-black transition-colors">
                        {language === 'ar' ? 'حفظ الإعدادات' : 'Save Settings'}
                    </button>

                    <p className="text-xs text-center text-gray-400 mt-4">
                        {language === 'ar' ? 'ملاحظة: يتطلب هذا إعداد Cron Job على السيرفر.' : 'Note: This requires Cron Job setup on server.'}
                    </p>
                </div>

                {/* Backups List */}
                <div className="lg:col-span-2 bg-white dark:bg-gray-800 rounded-[2rem] shadow-xl border border-gray-100 dark:border-gray-700 overflow-hidden">
                    <div className="p-6 border-b border-gray-100 dark:border-gray-700">
                        <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                            {language === 'ar' ? 'سجل النسخ الاحتياطية' : 'Backup History'}
                        </h3>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-gray-50 dark:bg-gray-900/50">
                                <tr>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'اسم الملف' : 'Filename'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'التاريخ' : 'Date'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'الحجم' : 'Size'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'تحميل' : 'Download'}
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
                                {loading ? (
                                    <tr>
                                        <td colSpan="4" className="px-6 py-12 text-center">
                                            <Loader2 className="animate-spin mx-auto text-purple-500" size={32} />
                                        </td>
                                    </tr>
                                ) : backups.length === 0 ? (
                                    <tr>
                                        <td colSpan="4" className="px-6 py-12 text-center text-gray-400">
                                            {language === 'ar' ? 'لم يتم العثور على نسخ احتياطية' : 'No backups found'}
                                        </td>
                                    </tr>
                                ) : (
                                    backups.map((file) => (
                                        <tr key={file.id} className="hover:bg-gray-50/50 dark:hover:bg-gray-800/50 transition-colors">
                                            <td className="px-6 py-4 text-sm font-bold text-gray-700 dark:text-gray-300 font-mono">
                                                {file.name}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500">
                                                {format(new Date(file.created_at), 'yyyy/MM/dd HH:mm')}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500">
                                                {(file.metadata?.size / 1024).toFixed(2)} KB
                                            </td>
                                            <td className="px-6 py-4">
                                                <button
                                                    onClick={() => handleDownload(file.name)}
                                                    className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                                    title="Download"
                                                >
                                                    <Download size={20} />
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
}
