-- Supabase Seed Data (Arabic & English Support)

-- 1. Seed Branches
INSERT INTO public.branches (name, location) VALUES 
('الفرع الرئيسي', 'الرياض'),
('فرع جدة', 'جدة');

-- 2. Seed Terminals (Linked to Branch 1 & 2)
-- Note: terminal_secret is auto-generated by gen_random_uuid in schema
INSERT INTO public.terminals (branch_id, name, connection_url) VALUES 
(1, 'كاشير 1 (الرئيسي)', 'cloud-sync'),
(1, 'كاشير 2 (المخزن)', 'cloud-sync'),
(2, 'كاشير جدة 1', 'cloud-sync');

-- 3. Sample Customers
INSERT INTO public.customers (full_name, phone, email, points_balance) VALUES 
('أحمد محمد', '0501234567', 'ahmed@example.com', 100),
('عمر خالد', '0507654321', 'omar@example.com', 50);

-- 4. Sample Cards (LINKED TO CUSTOMERS)
INSERT INTO public.cards (uid, customer_id) VALUES 
('ABC123456789', 1),
('XYZ987654321', 2);

-- 5. Sample Discounts
INSERT INTO public.discounts (name, type, value, points_required) VALUES 
('خصم ترحيبي', 'percentage', 10.00, 0),
('مكافأة العملاء الأوفياء', 'fixed_amount', 50.00, 100),
('مشروب مجاني', 'gift', 1.00, 50);

-- 6. System Settings
INSERT INTO public.settings (key_name, value) VALUES 
('currency_symbol', 'SAR'),
('points_ratio', '10');
